test: check sql is copied to container

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -58,6 +58,11 @@ jobs:
           CONTAINER_ID=$(docker ps -qf "ancestor=mysql:8.0")
           echo "Copying SQL file to MySQL container..."
           docker cp src/main/resources/cvt.sql $CONTAINER_ID:/cvt.sql
+          
+           echo "Verifying if SQL file was copied..."
+          docker exec $CONTAINER_ID ls /cvt.sql || { echo "SQL file not found in container"; exit 1; }
+
+
           echo "Executing SQL file..."
           docker exec $CONTAINER_ID mysql -uroot -pKarimax@2023 cvt_garage < /cvt.sql
 
